# generated by maixhub, tested on maixpy v0.6.0_2_g9720594
# copy files to TF card and plug into board and power on

import sensor, image, lcd, time
import KPU as kpu
import gc, sys
from machine import UART
from fpioa_manager import fm
#from gsm_modem import GSMModem
import time
import uio
from Maix import GPIO

input_size = (224, 224)
labels = ['sarna', 'dzik', 'kura', 'czlowiek']

class IOController:
    def __init__(self, pin, mode, fm, gpio):
        """
        Initialize the IOController for a specific pin.
        :param pin: The pin number to control.
        :param mode: The mode of the pin (e.g., fm.fpioa.GPIOHS0).
        :param fm: The fpioa_manager module.
        :param gpio: The GPIO module.
        """
        self.pin = pin
        self.mode = mode
        self.fm = fm
        self.gpio = gpio
        self._setup_pin()

    def _setup_pin(self):
        """
        Configure the pin for GPIO use.
        """
        self.fm.register(self.pin, self.mode, force=True)
        self.gpio_pin = self.gpio(self.mode, self.gpio.OUT)

    def set_high(self):
        """
        Set the pin to HIGH.
        """
        self.gpio_pin.value(1)

    def set_low(self):
        """
        Set the pin to LOW.
        """
        self.gpio_pin.value(0)

    def toggle(self):
        """
        Toggle the pin state.
        """
        current_state = self.gpio_pin.value()
        self.gpio_pin.value(1 - current_state)







class GSMModem:
    def __init__(self, uart, phone_number='48796070732'):
        self.uart = uart
        self.phone_number = phone_number

        # Komendy AT
        self.COMMAND_AT = "AT"
        self.AT_CSQ = "AT+CSQ"
        self.AT_COPS = "AT+COPS?"
        self.AT_CCID = "AT+CCID?"
        self.AT_CREG = "AT+CREG?"
        self.TEXT_MODE = "AT+CMGF=1"
        self.PREFIX_PHONE_NUMER = "AT+CMGS="
        self.RECIVE_SMS = "AT+CNMI=1,2,0,0,0"
        self.RECIVE_SMS2 = "AT+CMGL=\"ALL\""
        self.SET_DEFAULT_BAUDRATE = "AT+IPR=9600"
        self.DELETE_ALL_MESSAGES = "AT+CMGD=1,4"

    def send_command(self, cmd, delay=2):
        """Wysyła komendę i czeka na odpowiedź."""
        full_cmd = cmd + '\r\n'
        #print(f"[WYSYŁAM] {cmd}")
        self.uart.write(full_cmd.encode('utf-8'))
        time.sleep(delay)
        #self.read_response()

    def read_response(self):
        """Czyta dane z UART jeśli są dostępne."""
        #while self.uart.in_waiting:
            #data = self.uart.readline().decode('utf-8', errors='ignore').strip()
            #if data:
                #print(f"[ODEBRANO] {data}")

    def initialize_modem(self):
        self.send_command(self.COMMAND_AT)
        self.send_command(self.AT_CSQ)
        self.send_command(self.AT_COPS)
        self.send_command(self.AT_CREG)
        self.send_command(self.TEXT_MODE)

    def send_sms(self, msg):
        cmd = self.PREFIX_PHONE_NUMER + "\"+" + self.phone_number + "\""
        self.send_command(cmd, delay=4)

        self.uart.write(msg.encode('utf-8'))
        time.sleep(2)

        self.uart.write(chr(26).encode('utf-8'))  # CTRL+Z
        #print("[INFO] Wysłano znak końca wiadomości (CTRL+Z)")
        time.sleep(4)
        self.read_response()

    def manual_command(self, cmd):
        self.send_command(cmd)

class SimpleQueue:
    def __init__(self):
        self.data = []

    def append(self, item):
        self.data.append(item)

    def popleft(self):
        if self.data:
            return self.data.pop(0)
    def clean_all(self):
        self.data.clear()

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return self.data[index]

    def __bool__(self):
        return bool(self.data)

class DetectedObject:
    def __init__(self, max_seconds=5):
        self.max_seconds = max_seconds
        self.dzik = SimpleQueue()
        self.sarna = SimpleQueue()
        self.kura = SimpleQueue()
        self.czlowiek = SimpleQueue()

    def update(self, label):
        now = time.time()

        if label == 1:
            self.dzik.append(now)
        elif label == 2:
            self.sarna.append(now)
        elif label == 3:
            self.kura.append(now)
        elif label == 4:
            self.czlowiek.append(now)

        self._cleanup_old(now)

    def _cleanup_old(self, current_time):
        threshold = current_time - self.max_seconds
        for queue in [self.dzik, self.sarna, self.kura, self.czlowiek]:
            while queue and queue[0] < threshold:
                queue.popleft()

    def get_averages(self):
        # Zwraca "częstotliwość" wystąpień w ciągu 5 sekund
        return {
            "czlowiek": len(self.czlowiek) / self.max_seconds,
            "dzik": len(self.dzik) / self.max_seconds,
            "sarna": len(self.sarna) / self.max_seconds,
            "kura": len(self.kura) / self.max_seconds
        }
    def averages_clean_all(self):
        self.dzik.clean_all()
        self.sarna.clean_all()
        self.kura.clean_all()
        self.czlowiek.clean_all()


    def get_averages_dzik(self):
        return (len(self.dzik) / self.max_seconds)

    def get_averages_sarna(self):
        return (len(self.sarna) / self.max_seconds)

    def get_averages_kura(self):
        return (len(self.kura) / self.max_seconds)

    def get_averages_czlowiek(self):
        return (len(self.czlowiek) / self.max_seconds)

    def __str__(self):
        avg = self.get_averages()
        #return (f"Średnia (Hz) z ostatnich {self.max_seconds}s -> "
                #f"Człowiek: {avg['czlowiek']:.2f}, "
                #f"Dzik: {avg['dzik']:.2f}, "
                #f"Sarna: {avg['sarna']:.2f}, "
                #f"Kura: {avg['kura']:.2f}")

class Notifier:
    def __init__(self, time_to_wait):
        self.last_notification_time = 0
        self.cooldown_seconds = time_to_wait * 60  #
        self.active = False

    def notify(self, trigger, message, display):
        now = time.time()
        # Jeżeli trigger jest True i minęło 20 minut od ostatniego powiadomienia
        if trigger and (now - self.last_notification_time) > self.cooldown_seconds:
            self._show_message(message, display)
            self.last_notification_time = now

    def _show_message(self, message, display):
        display.draw_string(10, 100, message, scale=2, color=(255, 0, 0))
        lcd.display(display)
        time.sleep(3)
        lcd.clear()

def lcd_show_except(e):
    err_str = uio.StringIO()
    sys.print_exception(e, err_str)
    err_str = err_str.getvalue()
    img = image.Image(size=input_size)
    img.draw_string(0, 10, err_str, scale=1, color=(0xff,0x00,0x00))
    lcd.display(img)

class Comm:
    def __init__(self, uart):
        self.uart = uart

    def send_classify_result(self, pmax, idx, label):
        msg = "{}:{:.2f}:{}\n".format(idx, pmax, label)
        self.uart.write(msg.encode())

def init_uart():
    fm.register(10, fm.fpioa.UART1_TX, force=True)
    fm.register(11, fm.fpioa.UART1_RX, force=True)

    uart = UART(UART.UART1, 115200, 8, 0, 0, timeout=1000, read_buf_len=256)

    return uart

def init_uart_2():
    fm.register(16, fm.fpioa.UART2_TX, force=True)
    fm.register(17, fm.fpioa.UART2_RX, force=True)

    uart2 = UART(UART.UART2, 9600, 8, 0, 0, timeout=1000, read_buf_len=256)

    return uart2



def main(labels = None, model_addr=0x300000, sensor_window=input_size, sensor_hmirror=False, sensor_vflip=False):


    sensor.reset()
    sensor.set_pixformat(sensor.RGB565)
    sensor.set_framesize(sensor.QVGA)
    sensor.set_windowing(sensor_window)
    sensor.set_hmirror(sensor_hmirror)
    sensor.set_vflip(sensor_vflip)
    sensor.run(1)

    uart2 = init_uart_2()


    #modem = GSMModem(uart=uart2, phone_number='48796070732')
    #modem.initialize_modem()
    #time.sleep(10)
    #modem.send_sms("Uruchomiono urzędzenia")


    objects = DetectedObject()
    notify = Notifier(3)

    # Initialize IOController for pin 21 as output
    io_out_21 = IOController(pin=21, mode=fm.fpioa.GPIOHS0, fm=fm, gpio=GPIO)
    # Initialize IOController for pin 23 as output
    io_out_23 = IOController(pin=23, mode=fm.fpioa.GPIOHS0, fm=fm, gpio=GPIO)




    lcd.init(type=1 ) #?
    lcd.rotation(2)
    lcd.clear(lcd.WHITE)


    if not labels:
        with open('labels.txt','r') as f:
            exec(f.read())
    if not labels:
        print("no labels.txt")
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "no labels.txt", color=(255, 0, 0), scale=2)
        lcd.display(img)
        return 1
    try:
        img = image.Image("startup.jpg")
        lcd.display(img)
    except Exception:
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "loading model...", color=(255, 255, 255), scale=2)
        lcd.display(img)

    uart = init_uart()

    comm = Comm(uart)

    try:
        task = None
        task = kpu.load(model_addr)
        while(True):
            img = sensor.snapshot()
            t = time.ticks_ms()
            img.resize(320,224)
            fmap = kpu.forward(task, img)
            t = time.ticks_ms() - t
            plist=fmap[:]
            pmax=max(plist)

            max_index=plist.index(pmax)
            if labels[max_index].strip() == "dzik" and pmax > 0.70 :
                objects.update(1)
            if labels[max_index].strip() == "sarna" and pmax > 0.70 :
                objects.update(2)
            if labels[max_index].strip() == "kura" and pmax > 0.70 :
                objects.update(3)
            if labels[max_index].strip() == "czlowiek" and pmax > 0.90 :
                objects.update(4)

            if pmax > 0.70:
                img.draw_string(0,0, "%.2f : %s" %(pmax, labels[max_index].strip()), scale=2, color=(255, 0, 0))

                #objects_cout.update(labels[max_index].strip)
            #img.draw_string(0, 200, "t:%dms" %(t), scale=2, color=(255, 0, 0))
            if objects.get_averages_dzik() > 4.0 :
                objects.averages_clean_all()
                notify.notify(True, "Wykryto: DZIKA !", img)
            if objects.get_averages_sarna() > 4.0 :
                objects.averages_clean_all()
                notify.notify(True, "Wykryto: SARNA !", img)
            if objects.get_averages_kura() > 4.0 :
                objects.averages_clean_all()
                notify.notify(True, "Wykryto: KURA !", img)
            if objects.get_averages_czlowiek() > 5.5 :
                objects.averages_clean_all()
                notify.notify(True, "Wykryto: CZLOWIEK !", img)



            img.draw_string(0, 30, "dzik: %.2f" % objects.get_averages_dzik() , scale=1.2, color=(255, 0, 0))
            img.draw_string(0, 60, "sarna %.2f"% objects.get_averages_sarna() , scale=1.2, color=(255, 0, 0))
            img.draw_string(0, 90, "kura %.2f" % objects.get_averages_kura() , scale=1.2, color=(255, 0, 0))
            img.draw_string(0, 120, "czlowiek %.2f" % objects.get_averages_czlowiek() , scale=1.2, color=(255, 0, 0))


            comm.send_classify_result(pmax, max_index, labels[max_index].strip())
            lcd.display(img)
    except Exception as e:
        raise e
    finally:
        if not task is None:
            kpu.deinit(task)




if __name__ == "__main__":
    try:
        main(labels=labels, model_addr=0x300000)
    except Exception as e:
        sys.print_exception(e)
        lcd_show_except(e)
    finally:
        gc.collect()
